### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by firedigger** [Bauke/osu-streamkit#2]
I was thinking on a couple of trivial improvements to the program, for example:  
 - Make the checkboxes uneditable  
 - When the player is mapping, ",osu" is added to the title which is kinda redundant for the output  
  
However, the source code is missing from the repository, would you please upload it?

**Comment by Bauke** [comment]
I thought about making the checkboxes read only however the control isn't available by default so decided to leave it at that for now, I'm still looking into an alternative to show status.

I completely forgot to test mapping so that will definitely be fixed in the next release.

Source code is also coming!
Thank you for the feedback.
